# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GnsFtthToolbox
                                 A QGIS plugin
 FTTH plugin for GNS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-24
        copyright            : (C) 2024 by GNS
        email                : ftth@gns.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GnsFtthToolbox class from file GnsFtthToolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gns_ftth_toolbox import GnsFtthToolbox
    return GnsFtthToolbox(iface)
